#include <defs.h>
#include <stdio.h>
#include <string.h>
#include <console.h>
#include <kdebug.h>
#include <picirq.h>
#include <trap.h>
#include <clock.h>
#include <intr.h>
#include <pmm.h>
#include <kmonitor.h>
void lab1_print_cur_status(void);
void lab1_switch_to_user(void);
void lab1_switch_to_kernel(void);
